name: "CI [branch]"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.6"
          cache: true

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name:  Analyze project source
        run: |
          flutter analyze --fatal-infos
          flutter format --set-exit-if-changed .

      - name: Run tests
        run: flutter test
