name: "CI [branch]"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs: 
  build: 
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: configure enviroment
      uses: actions/checkout@v4
    - name: Get Flutter version by FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config-action
      with:
        path: '.fvmrc'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        cache: true
        cache-key: 'flutter-:os:-:version:'
        cache-path: '${{ runner.tool_cache }}/flutter/:os:-:version:'
    - name: get flutter dependencies
      run: flutter pub get
    - name: Verify formated files
      run: dart format . --set-exit-if-changed
    - name: code analyze 
      run: flutter analyze
    - name: Run tests
      run: flutter test
    - name: build web app
      run: flutter build web
    - name: build android app
      run: flutter build appbundle --debug
